version: "3.9"
services:
 mono:
  image: mono:latest
  container_name: m1
  ports:
   - "8080:8080"
  volumes:
   - /Users/aasrija/Documents/cmpt436/cmpt436Project/SOAP:/code
  stdin_open: true
  tty: true
 xsp1:
  image: hpgy/mono-xsp4
  container_name: x_1
  ports:
   - "8081:80"
  volumes:
   - /Users/aasrija/Documents/cmpt436/cmpt436Project/SOAP/app:/app
  stdin_open: true
  tty: true